spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/msb_dongbao_test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  redis:
    database: 0
    host: 192.168.144.200
    port: 6379
    password: 123456
    #      jedis:
    #        pool:
    #          max-active: 8
    #          max-wait: -1
    #          max-idle: 8
    #          min-idle: 0
    timeout: 500

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations:
  - classpath*:/com/msb/dongbao/ums/mapper/xml/*.xml
  type-aliases-package: com.msb.dongbao.ums.entity
kaptcha:
  height: 50
  width: 200
  content:
    length: 5
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: black
    name: Arial
    size: 40
  background-color:
    from: red
    to: white
  border:
    enabled: true
    color: black
    thickness: 1
server:
  port: 8081
